version: '3.8'

services:
  lavalink:
    image: fredboat/lavalink:latest
    container_name: lavalink
    ports:
      - "2333:2333"
    environment:
      - _JAVA_OPTIONS=-Xmx4G -Xms2G
      - SERVER_PORT=2333
      - LAVALINK_PASSWORD=$LAVALINK_PASS
    volumes:
      - ./application.yml:/opt/Lavalink/application.yml
  
  frieren:
    build: 
      context: ./bot
      dockerfile: Dockerfile
    
    depends_on:
      - lavalink
    env_file:
      - .env

